'use client';
import {useEffect,useState} from 'react';
import {ArrowLeft,CalendarDays,Clock,RefreshCw,ShieldCheck} from 'lucide-react';
import {useToday} from '../../use-today';
import {dateLabel} from '../../dates';
type Session={active:boolean;token?:string;meetingDay?:string;startsAt?:string;expiresAt?:string;nextStartAt?:string;url?:string;error?:string};
export default function QrDisplay(){const today=useToday();const [session,setSession]=useState<Session|null>(null),[image,setImage]=useState(''),[error,setError]=useState('');
useEffect(()=>{let live=true;let timer:number|undefined;const refresh=async()=>{try{const r=await fetch('/api/checkin/session',{cache:'no-store'});const b:Session=await r.json();if(!r.ok)throw Error(b.error||'QR indisponible');let src='';if(b.active&&b.url){const qr=await import('qrcode');src=await qr.toDataURL(b.url,{width:480,margin:2,color:{dark:'#001b35',light:'#ffffff'}});}if(live){setSession(b);setImage(src);setError('');}}catch(e){if(live)setError((e as Error).message);}finally{if(live)timer=window.setTimeout(refresh,15000);}};void refresh();return()=>{live=false;if(timer)window.clearTimeout(timer);};},[]);
return <main className="qr-display"><header><a href="/gestion"><ArrowLeft size={18}/> Espace responsable</a><img src="/logo-perseverants.png" alt="Les Persévérants"/></header><section className="qr-display-card"><p className="eyebrow">COM’FRAT · LES PERSÉVÉRANTS</p><h1>{session?.active?'Scannez pour confirmer votre présence':'QR du dimanche'}</h1><p className="qr-display-lede">{session?.active?'Un scan, puis votre présence est enregistrée.':'Le QR s’active automatiquement le samedi à 22 h.'}</p>{error?<div className="qr-display-state"><RefreshCw/><p>{error}</p><small>La page réessaie automatiquement.</small></div>:session?.active&&image?<><div className="qr-display-code"><img src={image} alt="QR collectif du dimanche"/></div><div className="qr-display-active"><span className="qr-live-dot"/> QR actif jusqu’au lundi à 22 h</div><p className="qr-display-date"><CalendarDays size={16}/> Rencontre du {dateLabel(session.meetingDay||today)}</p></>:<div className="qr-display-state"><Clock/><p>Le prochain QR apparaîtra ici automatiquement.</p><small>Prochaine ouverture : {dateLabel((session?.nextStartAt||today).slice(0,10))} à 22 h</small></div>}<div className="qr-display-foot"><ShieldCheck size={16}/> QR renouvelé chaque semaine · expiration automatique le lundi à 22 h</div></section><footer>Chaque personne compte. Vous aussi.</footer></main>;
}
