import {getChatGPTUser} from '../../chatgpt-auth';
import {db} from '../../../db/raw';
import {ensureSimpleAccess,grantTeamAccess,hasTeamAccess,recordTeamCodeAttempt,revokeTeamAccess,saveTeamCode,teamCodeAttemptsLimited,teamCodeExists,verifyTeamCode} from '../../feedback-access';

export const dynamic='force-dynamic';
const json=(data:unknown,status=200,headers:Record<string,string>={})=>Response.json(data,{status,headers:{'Cache-Control':'no-store',...headers}});
async function canSetup(){const user=await getChatGPTUser();if(!user)return false;const owner=await db().prepare("SELECT value FROM settings WHERE key='owner'").first<{value:string}>();return owner?.value===user.userId;}

export async function GET(req:Request){try{await ensureSimpleAccess();const setupRequired=!await teamCodeExists();return json({authorized:await hasTeamAccess(req),setupRequired,canSetup:setupRequired?await canSetup():false});}catch(e){console.error(e);return json({error:'La vérification de l’accès est indisponible.'},503);}}

export async function POST(req:Request){try{if(req.headers.get('origin')!==new URL(req.url).origin)return new Response(null,{status:403});await ensureSimpleAccess();const body=await req.json() as any;if(body.action==='logout')return json({ok:true},200,{'Set-Cookie':await revokeTeamAccess(req)});const configured=await teamCodeExists();if(body.action==='setup'){if(configured)return json({error:'Le code équipe est déjà configuré.'},409);if(!await canSetup())return json({error:'Connectez-vous avec le compte propriétaire pour configurer ce code.'},403);if(typeof body.code!=='string'||body.code.length<8||body.code.length>64)return json({error:'Choisissez un code d’au moins 8 caractères.'},400);await saveTeamCode(body.code);return json({ok:true},200,{'Set-Cookie':await grantTeamAccess(req)});}if(body.action==='unlock'){if(!configured)return json({error:'Le code équipe doit d’abord être configuré.'},409);if(await teamCodeAttemptsLimited(req))return json({error:'Trop d’essais. Réessayez dans 15 minutes.'},429);const valid=typeof body.code==='string'&&body.code.length<=64&&await verifyTeamCode(body.code);await recordTeamCodeAttempt(req,!!valid);if(!valid)return json({error:'Code incorrect.'},401);return json({ok:true},200,{'Set-Cookie':await grantTeamAccess(req)});}return json({error:'Action inconnue.'},400);}catch(e){console.error(e);return json({error:'Impossible de vérifier le code. Réessayez.'},503);}}
