import {getChatGPTUser} from '../../chatgpt-auth';
import {db} from '../../../db/raw';
import {ensureFeedbackTable} from '../../checkin-feedback';
import {codeAttemptsLimited,feedbackCodeExists,grantFeedbackAccess,hasFeedbackAccess,recordCodeAttempt,revokeFeedbackAccess,saveFeedbackCode,ensureSimpleAccess,verifyFeedbackCode} from '../../feedback-access';

export const dynamic='force-dynamic';
const json=(data:unknown,status=200,headers:Record<string,string>={})=>Response.json(data,{status,headers:{'Cache-Control':'no-store',...headers}});
async function canSetCode(){const user=await getChatGPTUser();if(!user)return false;const owner=await db().prepare("SELECT value FROM settings WHERE key='owner'").first<{value:string}>();return owner?.value===user.userId;}

export async function GET(req:Request){try{await ensureSimpleAccess();const configured=await feedbackCodeExists();if(!configured)return json({error:'Code d’accès à configurer.',setupRequired:true,canSetup:await canSetCode()},401);if(!await hasFeedbackAccess(req))return json({error:'Saisissez le code responsable pour lire ces partages.',setupRequired:false,canSetup:false},401);await ensureFeedbackTable();const rows=await db().prepare('SELECT c.*,p.first,p.last,p.status FROM checkin_feedback c JOIN people p ON p.id=c.person WHERE c.prayer_requested=1 OR c.testimony_requested=1 ORDER BY c.day DESC,c.created DESC').all();return json({feedback:rows.results});}catch(e){console.error(e);return json({error:'Les partages sont indisponibles. Réessayez.'},503);}}

export async function POST(req:Request){try{if(req.headers.get('origin')!==new URL(req.url).origin)return new Response(null,{status:403});await ensureSimpleAccess();const body=await req.json() as any;if(body.action==='logout')return json({ok:true},200,{'Set-Cookie':await revokeFeedbackAccess(req)});const configured=await feedbackCodeExists();if(body.action==='setup'){if(configured)return json({error:'Le code d’accès est déjà configuré.'},409);if(!await canSetCode())return json({error:'Connectez-vous avec le compte propriétaire pour configurer le code une première fois.'},403);if(typeof body.code!=='string'||body.code.length<8||body.code.length>64)return json({error:'Choisissez un code d’au moins 8 caractères.'},400);await saveFeedbackCode(body.code);const cookie=await grantFeedbackAccess(req);return json({ok:true},200,{'Set-Cookie':cookie});}if(body.action==='unlock'){if(!configured)return json({error:'Le code responsable doit d’abord être configuré.'},409);if(await codeAttemptsLimited(req))return json({error:'Trop d’essais. Réessayez dans 15 minutes.'},429);const valid=typeof body.code==='string'&&body.code.length<=64&&await verifyFeedbackCode(body.code);await recordCodeAttempt(req,!!valid);if(!valid)return json({error:'Code incorrect.'},401);const cookie=await grantFeedbackAccess(req);return json({ok:true},200,{'Set-Cookie':cookie});}return json({error:'Action inconnue.'},400);}catch(e){console.error(e);return json({error:'Impossible de vérifier le code. Réessayez.'},503);}}
