import assert from 'node:assert/strict';
const origin=process.env.ORIGIN||'http://localhost:5173';
const post=async(body)=>{const r=await fetch(origin+'/api/checkin',{method:'POST',headers:{'Content-Type':'application/json',Origin:origin},body:JSON.stringify(body)});return {status:r.status,data:await r.json()};};
const management=await fetch(origin+'/api/manage');assert.equal(management.status,401,'Management data must require the team code');assert.deepEqual(Object.keys(await management.json()),['error']);
const write=await fetch(origin+'/api/manage',{method:'POST',headers:{'Content-Type':'application/json',Origin:origin},body:JSON.stringify({action:'followup',id:'unknown',note:'No access'})});assert.equal(write.status,401,'Management changes must require the team code');
const feedback=await fetch(origin+'/api/feedback');assert.equal(feedback.status,401,'Prayer and testimony access must remain separately protected');
assert.equal((await post({first:'Incomplete'})).status,400);
const unique=Date.now();const person={first:'Test',last:'Verification'+unique,email:`test${unique}@example.invalid`,phone:'0600000000',city:'Paris',department:'75',status:'Invité',inviter:'Test Accueil'};
const created=await post(person);assert.equal(created.status,200,JSON.stringify(created));assert.ok(created.data.token);
const identify=await fetch(origin+'/api/checkin?token='+created.data.token);assert.deepEqual(await identify.json(),{first:'Test'});
assert.equal((await post({token:created.data.token})).status,200,'Participants must still be able to check in without management access');
assert.equal((await post(person)).status,409);
assert.equal((await post({token:'invalid'})).status,404);
const records=await fetch(origin+'/api/manage');assert.equal(records.status,401,'Public check-in must not grant access to personal data');
console.log('PASS: participant check-in remains public; management reads and writes and prayer/testimony reads require their separate protections.');
