import assert from 'node:assert/strict';
const origin=process.env.ORIGIN||'http://127.0.0.1:5188';
if(!['127.0.0.1','localhost'].includes(new URL(origin).hostname))throw Error('These tests must only run against the isolated local database.');
const owner={'oai-authenticated-user-id':'local-audit-owner','oai-authenticated-user-email':'local-owner@example.invalid'};
async function request(path,body,extra={}){const r=await fetch(origin+path,{method:body?'POST':'GET',headers:{Origin:origin,'Content-Type':'application/json',...extra},...(body?{body:JSON.stringify(body)}:{})});return {status:r.status,data:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]};}
assert.equal((await request('/api/access-recovery')).data.authorized,false);
assert.equal((await request('/api/access-recovery',{target:'team',code:'LocalTestTeam2026',confirmation:'LocalTestTeam2026'})).status,403);
assert.equal((await request('/api/access-recovery',null,owner)).data.authorized,true);
assert.equal((await request('/api/access-recovery',{target:'team',code:'LocalTestTeam2026',confirmation:'other'},owner)).status,400);
assert.equal((await request('/api/access-recovery',{target:'team',code:'LocalTestTeam2026',confirmation:'LocalTestTeam2026'},owner)).status,200);
const team=await request('/api/manage-access',{action:'unlock',code:'LocalTestTeam2026'});assert.equal(team.status,200);assert.ok(team.cookie);
assert.equal((await request('/api/manage',null,{Cookie:team.cookie})).status,200);
assert.equal((await request('/api/feedback',null,{Cookie:team.cookie})).status,401);
const session=await request('/api/checkin/session');assert.equal(session.data.active,true,'Run during the active test/weekly check-in window');
assert.equal((await request('/api/checkin?session='+session.data.token)).data.requiresLink,true);
const person={first:'Local',last:'Audit'+Date.now(),email:`audit${Date.now()}@example.invalid`,phone:'0600000000',city:'Paris',department:'75',status:'Invité',inviter:'Test local',session:session.data.token};
assert.equal((await request('/api/checkin',{...person,session:'expired'})).status,410);
const created=await request('/api/checkin',person);assert.equal(created.status,200,JSON.stringify(created));assert.equal(created.data.meetingDay,session.data.meetingDay);assert.equal(created.data.checkedIn,true);
const again=await request('/api/checkin',{session:session.data.token},{Cookie:created.cookie});assert.equal(again.status,200);assert.equal(again.data.alreadyPresent,true);
const data=await request('/api/manage',null,{Cookie:team.cookie});const p=data.data.people.find(p=>p.token===created.data.token);assert.ok(p);
assert.equal((await request('/api/manage',{action:'attend',id:p.id},{Cookie:team.cookie})).status,200);
const records=await request('/api/manage',null,{Cookie:team.cookie});assert.equal(records.data.attendance.filter(a=>a.person===p.id).length,1,'Team and QR must share the same attendance day');
const feedback=await request('/api/checkin/feedback',{token:created.data.token,day:session.data.meetingDay,prayerRequested:true,prayerText:'Sujet de test local',testimonyRequested:false,testimonyText:''});assert.equal(feedback.status,200);
assert.equal((await request('/api/access-recovery',{target:'feedback',code:'LocalPrayer2026',confirmation:'LocalPrayer2026'},owner)).status,200);
const prayer=await request('/api/feedback',{action:'unlock',code:'LocalPrayer2026'});assert.equal(prayer.status,200);assert.equal((await request('/api/feedback',null,{Cookie:prayer.cookie})).status,200);
assert.equal((await request('/api/access-recovery',{target:'feedback',code:'LocalPrayerNew2026',confirmation:'LocalPrayerNew2026'},owner)).status,200);
assert.equal((await request('/api/feedback',null,{Cookie:prayer.cookie})).status,401);
assert.equal((await request('/api/feedback',{action:'unlock',code:'LocalPrayer2026'})).status,401);
assert.equal((await request('/api/access-recovery',{target:'team',code:'LocalTeamNew2026',confirmation:'LocalTeamNew2026'},owner)).status,200);
assert.equal((await request('/api/manage',null,{Cookie:team.cookie})).status,401);
assert.equal((await request('/api/manage-access',{action:'unlock',code:'LocalTestTeam2026'})).status,401);
assert.equal((await request('/api/manage-access',{action:'unlock',code:'LocalTeamNew2026'})).status,200);
console.log('PASS: first collective scan registration, shared meeting dates, duplicate prevention, protected feedback and owner-only code rotation with session revocation.');
