import {meetingDayAt} from '../../meeting-calendar';
import {db} from '../../../db/raw';
import {ensureSimpleAccess,hasTeamAccess} from '../../feedback-access';
export const dynamic='force-dynamic';
const json=(data:unknown,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store'}});

export async function GET(req:Request){try{await ensureSimpleAccess();if(!await hasTeamAccess(req))return json({error:'Accès réservé à l’équipe de gestion.'},401);const d=db();const [people,attendance,followups]=await Promise.all([d.prepare('SELECT * FROM people ORDER BY created DESC').all(),d.prepare('SELECT * FROM attendance ORDER BY time DESC').all(),d.prepare('SELECT * FROM followups').all()]);return json({people:people.results,attendance:attendance.results,followups:followups.results});}catch(e){console.error(e);return json({error:'Les données sont indisponibles. Réessayez.'},503);}}

export async function POST(req:Request){try{if(req.headers.get('origin')!==new URL(req.url).origin)return new Response(null,{status:403});await ensureSimpleAccess();if(!await hasTeamAccess(req))return json({error:'Accès réservé à l’équipe de gestion.'},401);const body=await req.json() as any,d=db();let token:string|undefined;if(body.action==='followup'){if(typeof body.note!=='string'||body.note.length>2000||typeof body.id!=='string')return json({error:'Note de suivi invalide.'},400);await d.prepare('INSERT INTO followups(person,note,updated) VALUES(?,?,?) ON CONFLICT(person) DO UPDATE SET note=excluded.note,updated=excluded.updated').bind(body.id,body.note,new Date().toISOString()).run();}else if(body.action==='attend'){if(typeof body.id!=='string')return json({error:'Fiche introuvable.'},400);const day=meetingDayAt();await d.prepare('INSERT OR IGNORE INTO attendance(person,day,time,mode) VALUES(?,?,?,?)').bind(body.id,day,new Date().toISOString(),'Équipe').run();}else if(body.action==='replaceQr'){if(typeof body.id!=='string'||!body.id||body.id.length>100)return json({error:'Fiche introuvable.'},400);const existing=await d.prepare('SELECT id FROM people WHERE id=?').bind(body.id).first<{id:string}>();if(!existing)return json({error:'Cette fiche n’existe plus.'},404);token=crypto.randomUUID()+crypto.randomUUID();await d.prepare('UPDATE people SET token=? WHERE id=?').bind(token,body.id).run();}else return json({error:'Action inconnue.'},400);return json({ok:true,...(token?{token}:{})});}catch(e){console.error(e);return json({error:'Enregistrement impossible.'},400);}}
