import {sunday} from './dates';
export {parisDay,sunday,dateLabel} from './dates';
export const PERSON_STATUSES = ['Membre', 'Nouveau', 'NA', 'NC', 'Invité'];
export type Person={id:string,first:string,last:string,email:string,phone:string,city:string,department:string,status:string,inviter:string,token:string,created:string};
export type Attendance={person:string,day:string,time:string,mode:string};
export function indicator(p:Person,a:Attendance[]){const visits=a.filter(x=>x.person===p.id);const last=visits.map(x=>x.day).sort().at(-1);const missing=Math.max(0,Math.ceil((Date.parse(sunday())-Date.parse(last||p.created.slice(0,10)))/604800000));if(missing>=3)return {label:'Absent depuis 3 dimanches ou +',short:'3 dimanches ou +',color:'red'};if(missing>=2)return {label:'Absent depuis 2 dimanches',short:'2 dimanches',color:'orange'};if(p.status==='Invité'&&visits.length<=1)return {label:'Nouvel invité',short:'Nouvel invité',color:'purple'};if(missing>=1||['Nouveau','NA','NC','NA-NC'].includes(p.status))return {label:'À suivre',short:'À suivre',color:'yellow'};return {label:'Régulier',short:'Régulier',color:'green'};}
const names=[['Sarah','Martin','Membre'],['David','Kouassi','Membre'],['Esther','Diallo','Invité'],['Samuel','Mbaye','Membre'],['Grâce','Benoît','NA'],['Emmanuel','Petit','Membre'],['Rebecca','Mensah','Invité'],['Joshua','Laurent','Membre'],['Déborah','Moreau','NC'],['Nathan','Dupont','Nouveau'],['Marie','Lefèvre','Membre'],['Paul','Bernard','Membre']];
export const demoPeople:Person[]=names.map(([first,last,status],i)=>({id:String(i),first,last,status,email:first.toLowerCase()+'@exemple.fr',phone:'',city:'Paris',department:'75',inviter:status==='Invité'?'Sarah Martin':'',token:'',created:sunday(-8)+'T09:00:00Z'}));
export const demoAttendance:Attendance[]=demoPeople.flatMap((p,i)=>Array.from({length:8},(_,w)=>({person:p.id,day:sunday(-w),time:sunday(-w)+`T09:${String(i*4).padStart(2,'0')}:00Z`,mode:i%2?'QR personnel':'Équipe'})).filter((a,w)=>p.status==='Invité'?w===0:i===3?w>=3:i===5?w>=2:i===8?w>=1:(i+w)%5!==0));
