'use client';
import {useEffect,useState} from 'react';
import {ArrowLeft,Check,ShieldCheck} from 'lucide-react';
import PasswordInput from '../../password-input';
export default function Recovery(){
 const [access,setAccess]=useState('checking'),[target,setTarget]=useState<'team'|'feedback'>('team'),[code,setCode]=useState(''),[confirmation,setConfirmation]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState(false);
 async function check(){setError('');try{const r=await fetch('/api/access-recovery',{cache:'no-store'});const b=await r.json() as {error?:string;authorized?:boolean;status?:string};if(!r.ok)throw Error(b.error||'Service indisponible');setAccess(b.authorized?'owner':(b.status||'sign_in_required'));}catch(e){setAccess('error');setError((e as Error).message);}}
 useEffect(()=>{void check();},[]);
 async function save(e:React.FormEvent){e.preventDefault();setError('');if(code!==confirmation){setError('Les deux codes ne correspondent pas.');return;}setBusy(true);try{const r=await fetch('/api/access-recovery',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({target,code,confirmation})});const b=await r.json() as {error?:string;authorized?:boolean;status?:string};if(!r.ok)throw Error(b.error||'Service indisponible');setCode('');setConfirmation('');setSaved(true);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <main className="access-page"><section className="card access-card"><img className="access-logo" src="/logo-perseverants.png" alt="Les Persévérants"/><p className="eyebrow">COM’FRAT · ACCÈS PROPRIÉTAIRE</p><h1>Modifier un code d’accès</h1><p className="access-intro">Le propriétaire peut choisir un nouveau code, même si l’ancien a été oublié.</p>{access==='checking'?<p role="status">Vérification…</p>:access==='owner'?saved?<div className="recovery-success" role="status"><Check/><p>Le code {target==='team'?'de l’équipe':'responsable'} a été modifié. Les anciennes sessions ont été fermées. Partagez le nouveau code uniquement avec les personnes autorisées.</p><button className="secondary" onClick={()=>setSaved(false)}>Modifier un autre code</button></div>:<form className="feedback-code-form" onSubmit={save}><label>Code à modifier<select value={target} onChange={e=>setTarget(e.target.value as 'team'|'feedback')}><option value="team">Code de l’équipe</option><option value="feedback">Code responsable · Prières et témoignages</option></select></label><label>Nouveau code<PasswordInput aria-label="Nouveau code" autoComplete="new-password" required minLength={8} maxLength={64} value={code} onChange={e=>setCode(e.target.value)}/></label><label>Confirmer le nouveau code<PasswordInput aria-label="Confirmer le nouveau code" autoComplete="new-password" required minLength={8} maxLength={64} value={confirmation} onChange={e=>setConfirmation(e.target.value)}/></label><small>Au moins 8 caractères. Les sessions utilisant l’ancien code seront fermées.</small><button className="primary" disabled={busy}>{busy?'Modification…':'Enregistrer le nouveau code'}</button></form>:<div className="access-owner-help"><ShieldCheck/><p>{access==='different_account'?'Ce compte n’est pas le propriétaire du site. Connectez-vous avec le compte propriétaire.':'Connectez-vous comme propriétaire pour modifier les codes en sécurité.'}</p><a className="primary" href="/signin-with-chatgpt?return_to=%2Fgestion%2Frecuperation" target="_top">Se connecter comme propriétaire</a>{access==='different_account'&&<a className="text-link" href="/signout-with-chatgpt?return_to=%2Fgestion%2Frecuperation" target="_top">Changer de compte</a>}<button className="secondary" onClick={()=>void check()}>Vérifier ma connexion</button></div>}{error&&<p className="form-error" role="alert">{error}</p>}<a className="secondary access-checkin-link" href="/gestion"><ArrowLeft size={16}/> Retour à l’espace équipe</a></section></main>;
}
